//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAPHANG
    {
        public CHITIETPHIEUNHAPHANG()
        {
            this.CONGNOCHI = new HashSet<CONGNOCHI>();
        }
    
        public string MaChiTietPhieuNhapHang { get; set; }
        public string MaPhieuNhapHang { get; set; }
        public string MaHangHoa { get; set; }
        public int SoLuong { get; set; }
        public decimal ThanhTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual PHIEUNHAPHANG PHIEUNHAPHANG { get; set; }
        public virtual ICollection<CONGNOCHI> CONGNOCHI { get; set; }
    }
}
