//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUCNANG
    {
        public CHUCNANG()
        {
            this.PHANQUYEN = new HashSet<PHANQUYEN>();
        }
    
        public string MaChucNang { get; set; }
        public string TenChucNang { get; set; }
        public string DienGiai { get; set; }
    
        public virtual ICollection<PHANQUYEN> PHANQUYEN { get; set; }
    }
}
