//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGNOTHU
    {
        public string MaCongNoThu { get; set; }
        public string MaChiTietPhieuBanHang { get; set; }
        public decimal SoTienDaTra { get; set; }
        public decimal SoTienConLai { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string DienGiai { get; set; }
    
        public virtual CHITIETPHIEUBANHANG CHITIETPHIEUBANHANG { get; set; }
    }
}
