//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        public HANGHOA()
        {
            this.CHITIETPHIEUBANHANG = new HashSet<CHITIETPHIEUBANHANG>();
            this.CHITIETPHIEUCHUYENKHO = new HashSet<CHITIETPHIEUCHUYENKHO>();
            this.CHITIETPHIEUNHAPHANG = new HashSet<CHITIETPHIEUNHAPHANG>();
            this.TONKHO = new HashSet<TONKHO>();
        }
    
        public string MaHangHoa { get; set; }
        public string TenHangHoa { get; set; }
        public string LoaiHang { get; set; }
        public string MaKho { get; set; }
        public string MaNhomHang { get; set; }
        public string MaDonVi { get; set; }
        public string VachNhaSX { get; set; }
        public string XuatXu { get; set; }
        public string MaNhaCungCap { get; set; }
        public decimal GiaMua { get; set; }
        public decimal GiaBanLe { get; set; }
        public decimal GiaBanSi { get; set; }
        public int TonKhoToiThieu { get; set; }
        public int TonKhoHienTai { get; set; }
        public Nullable<bool> ConQuanLyHangHoa { get; set; }
    
        public virtual ICollection<CHITIETPHIEUBANHANG> CHITIETPHIEUBANHANG { get; set; }
        public virtual ICollection<CHITIETPHIEUCHUYENKHO> CHITIETPHIEUCHUYENKHO { get; set; }
        public virtual ICollection<CHITIETPHIEUNHAPHANG> CHITIETPHIEUNHAPHANG { get; set; }
        public virtual DONVITINH DONVITINH { get; set; }
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHOMHANG NHOMHANG { get; set; }
        public virtual ICollection<TONKHO> TONKHO { get; set; }
    }
}
