//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOHANG
    {
        public KHOHANG()
        {
            this.HANGHOA = new HashSet<HANGHOA>();
            this.PHIEUBANHANG = new HashSet<PHIEUBANHANG>();
            this.PHIEUCHUYENKHO = new HashSet<PHIEUCHUYENKHO>();
            this.PHIEUCHUYENKHO1 = new HashSet<PHIEUCHUYENKHO>();
            this.PHIEUNHAPHANG = new HashSet<PHIEUNHAPHANG>();
            this.TONKHO = new HashSet<TONKHO>();
        }
    
        public string MaKho { get; set; }
        public string TenKho { get; set; }
        public string NguoiQuanLy { get; set; }
        public string NguoiLienHe { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public string KyHieu { get; set; }
        public string GhiChu { get; set; }
        public string Email { get; set; }
        public Nullable<bool> ConQuanLyKhoHang { get; set; }
    
        public virtual ICollection<HANGHOA> HANGHOA { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual ICollection<PHIEUBANHANG> PHIEUBANHANG { get; set; }
        public virtual ICollection<PHIEUCHUYENKHO> PHIEUCHUYENKHO { get; set; }
        public virtual ICollection<PHIEUCHUYENKHO> PHIEUCHUYENKHO1 { get; set; }
        public virtual ICollection<PHIEUNHAPHANG> PHIEUNHAPHANG { get; set; }
        public virtual ICollection<TONKHO> TONKHO { get; set; }
    }
}
