//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUVUC
    {
        public KHUVUC()
        {
            this.KHACHHANG = new HashSet<KHACHHANG>();
            this.NHACUNGCAP = new HashSet<NHACUNGCAP>();
        }
    
        public string MaKhuVuc { get; set; }
        public string TenKhuVuc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> ConQuanLyKhuVuc { get; set; }
    
        public virtual ICollection<KHACHHANG> KHACHHANG { get; set; }
        public virtual ICollection<NHACUNGCAP> NHACUNGCAP { get; set; }
    }
}
