//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACUNGCAP
    {
        public NHACUNGCAP()
        {
            this.HANGHOA = new HashSet<HANGHOA>();
            this.PHIEUNHAPHANG = new HashSet<PHIEUNHAPHANG>();
        }
    
        public string MaNhaCungCap { get; set; }
        public string TenNhaCungCap { get; set; }
        public string MaKhuVuc { get; set; }
        public string NguoiLienHe { get; set; }
        public string ChucVu { get; set; }
        public string DiaChi { get; set; }
        public string MaSoThue { get; set; }
        public string DienThoai { get; set; }
        public string DiDong { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string SoTaiKhoan { get; set; }
        public string TenNganHang { get; set; }
        public Nullable<decimal> ChietKhau { get; set; }
        public Nullable<decimal> GioiHanNo { get; set; }
        public Nullable<decimal> NoHienTai { get; set; }
        public Nullable<bool> ConQuanLyNhaCungCap { get; set; }
    
        public virtual ICollection<HANGHOA> HANGHOA { get; set; }
        public virtual KHUVUC KHUVUC { get; set; }
        public virtual ICollection<PHIEUNHAPHANG> PHIEUNHAPHANG { get; set; }
    }
}
