//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.KHOHANG = new HashSet<KHOHANG>();
            this.PHIEUNHAPHANG = new HashSet<PHIEUNHAPHANG>();
            this.NHANVIEN1 = new HashSet<NHANVIEN>();
            this.PHIEUBANHANG = new HashSet<PHIEUBANHANG>();
            this.PHIEUCHUYENKHO = new HashSet<PHIEUCHUYENKHO>();
            this.PHIEUCHUYENKHO1 = new HashSet<PHIEUCHUYENKHO>();
            this.TAIKHOAN = new HashSet<TAIKHOAN>();
        }
    
        public string MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public string MaBoPhan { get; set; }
        public string ChucVu { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string DiDong { get; set; }
        public string QuanLy { get; set; }
        public Nullable<bool> ConQuanLyNhanVien { get; set; }
    
        public virtual BOPHAN BOPHAN { get; set; }
        public virtual ICollection<KHOHANG> KHOHANG { get; set; }
        public virtual ICollection<PHIEUNHAPHANG> PHIEUNHAPHANG { get; set; }
        public virtual ICollection<NHANVIEN> NHANVIEN1 { get; set; }
        public virtual NHANVIEN NHANVIEN2 { get; set; }
        public virtual ICollection<PHIEUBANHANG> PHIEUBANHANG { get; set; }
        public virtual ICollection<PHIEUCHUYENKHO> PHIEUCHUYENKHO { get; set; }
        public virtual ICollection<PHIEUCHUYENKHO> PHIEUCHUYENKHO1 { get; set; }
        public virtual ICollection<TAIKHOAN> TAIKHOAN { get; set; }
    }
}
