//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUBANHANG
    {
        public PHIEUBANHANG()
        {
            this.CHITIETPHIEUBANHANG = new HashSet<CHITIETPHIEUBANHANG>();
        }
    
        public string MaPhieuBanHang { get; set; }
        public string MaKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string GhiChu { get; set; }
        public string NhanVien { get; set; }
        public string KhoXuat { get; set; }
        public string DieuKhoanThanhToan { get; set; }
        public string HinhThucThanhToan { get; set; }
        public Nullable<System.DateTime> HanThanhToan { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
    
        public virtual ICollection<CHITIETPHIEUBANHANG> CHITIETPHIEUBANHANG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
    }
}
