//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUCHUYENKHO
    {
        public string MaPhieuChuyenKho { get; set; }
        public string KhoXuatHang { get; set; }
        public string NguoiChuyen { get; set; }
        public string KhoNhanHang { get; set; }
        public string NguoiNhan { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayChuyen { get; set; }
    
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual KHOHANG KHOHANG1 { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
    }
}
