//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO
    {
        public string MaKho { get; set; }
        public string MaHangHoa { get; set; }
        public Nullable<int> SLTonToiThieu { get; set; }
        public Nullable<int> SLTonHienTai { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual KHOHANG KHOHANG { get; set; }
    }
}
